<?php
// Customize init
$Customize = [
	'header_version' => LAYOUT_HEADER_VERSION,
	'show_top_header' => 1,
	'show_header_banner' => 1,
	'show_breadcrumb' => 1,
	'show_main_slideshow' => 1,
	'home_layout' => 'full',
	'home_page_intro' => '',
	'page_layout' => 'right-sidebar',
	'single_layout' => 'right-sidebar',
	'archive_layout' => 'right-sidebar',
	'show_footer_layout' => 1,
	'footer_layout' => '3c',
	'show_footer_copyright' => 1,
	'show_client' => -1,
	'show_face_fanpage_plugin' => 1,
	'header_background_color' => '#fff',
	'header_background_color_fixed' => '#fff',
	'header_home_icon_color' => '#fff',
	'header_link_color' => '#333',
	'header_hover_link_color' => '#333',
	'header_background_submenu' => '#fff',
	'header_link_color_sub' => '#333',
	'header_link_color_sub_hover' => '#333',

	'ws24h_hotline_number' => '0909874825',
	'ws24h_zalo_number' => '0909874825',
	'ws24h_sms_number' => '0909874825',
 
    'company_name' => __('Company name', THEMENAME),
    'company_footer_name' => __('Company footer name', THEMENAME),
    'contact_address' => __('XXX Nguyễn Thị Đặng, Tân Thới Hiệp, Q.12, Tp.HCM', THEMENAME),
    'contact_email' => __('dbthanhbinh@gmail.com', THEMENAME),
    'contact_phone' => __('0909874825', THEMENAME),
    'contact_hotline' => __('0909874825', THEMENAME),
    'setting_copyright' => __('© WEBSEO24H. All Rights Reserved', THEMENAME),
    'setting_open_time' => __('Từ 8:00 - 19:00 tất cả các ngày trong tuần, kể cả ngày lễ', THEMENAME),
    'google_analytics_code' => __('UA-xxxxxxxxx', THEMENAME),
	'google_site_verification' => '',

    'facebook_name' => __('webseo24h', THEMENAME),
    'facebook_link' => __('https://www.facebook.com/webseo24h', THEMENAME),
    'youtube_link' => __('https://www.youtube.com/', THEMENAME),
    'zalo_link' => __('https://chat.zalo.me/', THEMENAME),
    'google_plus_link' => __('https://google.com.vn', THEMENAME),
    'twitter_link' => __('https://twitter.com/', THEMENAME),
];